# Generated by Django 6.0.1 on 2026-03-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
