# Generated by Django 6.0.1 on 2026-03-09 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_appointment_status_medicalreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHealthData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('blood_pressure', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('oxygen_level', models.IntegerField()),
                ('blood_sugar', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('hemoglobin', models.FloatField()),
                ('symptoms', models.TextField()),
                ('disease_history', models.TextField()),
                ('medications', models.TextField()),
                ('allergies', models.TextField()),
                ('smoking', models.CharField(max_length=10)),
                ('alcohol', models.CharField(max_length=10)),
                ('exercise', models.CharField(max_length=20)),
                ('sleep_hours', models.IntegerField()),
                ('family_diabetes', models.CharField(max_length=10)),
                ('family_heart', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
